from pathlib import Path

index = Path('index.html').read_text(encoding='utf-8')
operations = Path('operations-messages.html').read_text(encoding='utf-8')
voip = Path('voip-finder.html').read_text(encoding='utf-8')
owner = Path('system-owner-finder.html').read_text(encoding='utf-8')
generator = Path('scripts/add-responsive-fit.py')

for name, html in [('main', index), ('operations', operations), ('voip', voip), ('owner', owner)]:
    assert 'name="viewport"' in html, f'{name} page must keep a viewport meta tag'

assert generator.exists(), 'responsive fit must be generated by scripts/add-responsive-fit.py so workflow runs preserve it'
responsive_generator = generator.read_text(encoding='utf-8')

required_main = [
    '/* responsive-fit-v1 */',
    '100dvh',
    '100svh',
    'clamp(',
    '@media(max-height:760px)',
    '@media(max-width:767px)',
    'env(safe-area-inset-',
]
for needle in required_main:
    assert needle in index, f'main page missing adaptive responsive contract: {needle}'
    assert needle in responsive_generator, f'responsive generator must preserve: {needle}'

# Utility workspaces must size from the viewport instead of a hard-coded mobile canvas.
for stale in [
    '#view-system-owner,#view-voip,#view-operations{min-height:820px}',
    '.utility-workspace-shell{height:820px;min-height:820px}',
]:
    assert stale not in index, f'fixed Utility height blocks viewport adaptation: {stale}'

# Topbar and workspace must be able to wrap/scroll without causing horizontal page overflow.
for needle in [
    'overflow-x:hidden',
    '.topbar{',
    'flex-wrap:wrap',
    '.content-main{',
    '.workspace-shell{',
]:
    assert needle in index, f'main responsive layer missing layout safeguard: {needle}'

# Operations cards must collapse fluidly instead of relying only on fixed 3/2-column layouts.
for needle in ['/* responsive-fit-v1 */', 'auto-fit', 'minmax(min(100%', 'clamp(']:
    assert needle in operations, f'Operations Messages missing fluid layout behavior: {needle}'

# Embedded tools must explicitly prevent horizontal overflow and remain usable inside a resized iframe.
for name, html in [('voip', voip), ('owner', owner)]:
    assert 'responsive-fit-v1' in html, f'{name} loader must include responsive-fit bridge styles'
    assert 'overflow-x:hidden' in html, f'{name} loader must prevent horizontal overflow'
    assert 'max-width:100%' in html, f'{name} loader content must fit the iframe width'

print('responsive fit v1 adaptive layout contract: OK')
